for file in $XDG_CONFIG_HOME/zsh/*.zsh; do
	source $file
done

defaults write org.hammerspoon.Hammerspoon MJConfigFile "$XDG_CONFIG_HOME/hammerspoon/init.lua"

eval "$(mise activate zsh)"
eval "$(starship init zsh)"
